version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - docker build -t gabrielltr/droneproducer:latest ./droneproducer
      - docker build -t gabrielltr/dronebackend:latest ./dronebackend
      - docker build -t gabrielltr/icc-react-web-app:latest ./icc-react-web-app
      - docker build -t gabrielltr/loadbalance:latest ./loadbalance
  post_build:
    commands:
      - echo Build completed on `date`
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push gabrielltr/droneproducer
      - docker push gabrielltr/droneproducer
      - docker push gabrielltr/icc-react-web-app
      - docker push gabrielltr/loadbalance
      - echo Push completed on `date`
