version: '3.7'

services:

  rabbit:
    image: rabbitmq:3-management
    #ports:
      #- 15672:15672
      #- 5672:5672
    #healthcheck:
#      test: [ "CMD", "rabbitmqctl" ,"node_health_check" ]
      #test: ["CMD", "rabbitmq-diagnostics", "check_running", "--timeout", "10"]
      #timeout: 50s
      #retries: 10
    #    command: rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - ms_network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      # - db_scripts/create-db.sql:/docker-entrypoint-initdb.d/001_create-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: 987654321
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: fiappass
      MYSQL_DATABASE: droneDB
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ms_network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - ms_network

  drone:
    image: gabrielltr/dronebackend:$MS_VERSION
    #build: ./droneBackend/
    depends_on:
      - db
      - rabbit
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 1m10s
      timeout: 10s
      retries: 3
      #start_period: 40s
    #command: "echo INICIANDO && curl -f "
    deploy:
      replicas: 2
    ports:
      - 8090:8090
    environment:
      SPRING_APPLICATION_JSON: "{}"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 987654321
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/droneDB?serverTimezone=UTC
    networks:
      - ms_network

  icc-react-web-app:
    image: gabrielltr/icc-react-web-app:${WEB_VERSION}
    #build: ./icc-react-web-app/
    ports:
      - 80:80
    environment:
      REACT_APP_GMAPSKEY: $${${REACT_APP_GMAPSKEY}:AIzaSyD0Rl8_u08deZdD9QJuBWvXmw94lEJlNy0}
volumes:
  db-data:

networks:
  ms_network:
