server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/droneDB?serverTimezone=UTC
    username: root
    password: 30914182
    hikari:
      maximum-pool-size: 2
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # Show or not log for each sql query
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

    hibernate:
#      Hibernate ddl auto (create, create-drop, update)
#      ddl-auto: create-drop
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
    env:
      enabled: true

#
#spring-boot:
#  build-image:
#    imageName: docker.io/library/gabrielltr/${project.artifactId}:${project.version}