server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:~/fiapDroneDatabase;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update

  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
      enabled: true